networks:
  projetos-vps:
    external: true

services:
  mailcleaner:
    build: .
    image: mdk/mailcleaner:1.0
    container_name: mailcleaner
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PW: password
      REDIS_CHANNELS: channel_test,channel_test_2
    networks:
      - projetos-vps
    restart: unless-stopped
